### ISSUE TITLE
Doesnt seem to work

### ISSUE THREAD

**Issue by nhumrich** [yasintoy/Slack-Gitsin#24]
readme shows you start by running `python main.py`, but all I get is the following

```
$ python main.py 
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    from utils import TextUtils
  File "/home/nhumrich/open-source/Slack-Gitsin/slackClient/utils.py", line 13, in <module>
    from completions import META_LOOKUP
  File "/home/nhumrich/open-source/Slack-Gitsin/slackClient/completions.py", line 13, in <module>
    user_id = response["user_id"]
KeyError: 'user_id'
```

**Comment by yigitozkavci** [comment]
Did you add your api key to `settings.py`?

**Comment by yigitozkavci** [comment]
We should give user a helpful error when s/he is using a wrong api key. I'm working on it.
