### ISSUE TITLE
Turkish character problem

### ISSUE THREAD

**Issue by masingacom** [yasintoy/Slack-Gitsin#7]
"Merhaba Dünya" :(

slack> slack chat.postMessage "Merhaba DüException in thread Thread-77:
Traceback (most recent call last):  
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()  
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/Users/gokhan/Documents/env/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 835, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/Users/gokhan/Documents/Slack-Gitsin/slackClient/utils.py", line 25, in find_matches
    word, collection, fuzzy):
  File "/Users/gokhan/Documents/Slack-Gitsin/slackClient/utils.py", line 83, in _find_collection_matches
    if name.lower().startswith(word) or not word:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

saj" general gakgak

**Comment by yasintoy** [comment]
Usage : slack> slack slack chat.postMessage "Send" channel_name 
It's not problem.You're writing wrong syntax. Try like above or I recommend you watch to gif in the README.
